default: &default
  adapter: "postgresql"
  host: "containers-us-west-156.railway.app"
  username: "postgres"
  password: "eVmOOJ7jm4D6mF2IA1l9"
  port: 6586

development:
  <<: *default
  database: railway

test:
  <<: *default
  database: railway

production:
  <<: *default
  database: railway
